Traceback (most recent call last):
  File "/home/roma/anaconda3/lib/python3.9/site-packages/gymnasium/envs/classic_control/cartpole.py", line 223, in render
    import pygame
ModuleNotFoundError: No module named 'pygame'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/roma/animal-ai/agents/dqn.py", line 175, in <module>
    obs, _ = envs.reset(seed=args.seed)
  File "/home/roma/anaconda3/lib/python3.9/site-packages/gymnasium/vector/vector_env.py", line 139, in reset
    return self.reset_wait(seed=seed, options=options)
  File "/home/roma/anaconda3/lib/python3.9/site-packages/gymnasium/vector/sync_vector_env.py", line 122, in reset_wait
    observation, info = env.reset(**kwargs)
  File "/home/roma/anaconda3/lib/python3.9/site-packages/gymnasium/wrappers/record_episode_statistics.py", line 73, in reset
    obs, info = super().reset(**kwargs)
  File "/home/roma/anaconda3/lib/python3.9/site-packages/gymnasium/core.py", line 414, in reset
    return self.env.reset(seed=seed, options=options)
  File "/home/roma/anaconda3/lib/python3.9/site-packages/gymnasium/wrappers/record_video.py", line 118, in reset
    self.start_video_recorder()
  File "/home/roma/anaconda3/lib/python3.9/site-packages/gymnasium/wrappers/record_video.py", line 137, in start_video_recorder
    self.video_recorder.capture_frame()
  File "/home/roma/anaconda3/lib/python3.9/site-packages/gymnasium/wrappers/monitoring/video_recorder.py", line 114, in capture_frame
    frame = self.env.render()
  File "/home/roma/anaconda3/lib/python3.9/site-packages/gymnasium/core.py", line 418, in render
    return self.env.render()
  File "/home/roma/anaconda3/lib/python3.9/site-packages/gymnasium/wrappers/order_enforcing.py", line 70, in render
    return self.env.render(*args, **kwargs)
  File "/home/roma/anaconda3/lib/python3.9/site-packages/gymnasium/wrappers/env_checker.py", line 63, in render
    return env_render_passive_checker(self.env, *args, **kwargs)
  File "/home/roma/anaconda3/lib/python3.9/site-packages/gymnasium/utils/passive_env_checker.py", line 391, in env_render_passive_checker
    result = env.render()
  File "/home/roma/anaconda3/lib/python3.9/site-packages/gymnasium/envs/classic_control/cartpole.py", line 226, in render
    raise DependencyNotInstalled(
gymnasium.error.DependencyNotInstalled: pygame is not installed, run `pip install gymnasium[classic-control]`